### PR TITLE
Allow variablisation of the database pool config, non-breaking change

### PR DESCRIPTION
**Pull request by aneurinprice**
## Checklist

🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository. 🚨

- [X] Make sure you are making a pull request against our **main branch** (left side)
- [X] Check that that your branch is up to date with our main.
- [] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request *your* main!
- [ ] Check that the tests and code linter both pass.
- [ ] If you're a new contributor, please sign our [contributor license agreement](https://cla-assistant.io/manyfold3d/manyfold).

## Warnings

- [ ] This PR will change existing database contents.
- [ ] This PR introduces a breaking change to existing installations.

## Linked issues

https://github.com/manyfold3d/manyfold/issues/2288

## Description of changes

Variablise the database connection pool in docker environment.

### CODE REVIEW

**Comment by aneurinprice** [comment]
@Floppy looks like docker builds are unhappy.

**Comment by Floppy** [comment]
They always are with forks. I should fix that... somehow.

**Review by Floppy — APPROVED** [review]

**Comment by aneurinprice** [comment]
May I suggest https://github.com/GoogleContainerTools/kaniko that's what I use on my (gitlab)[https://gitlab.nyeprice.space]

**Comment by Floppy** [comment]
We fire off the builds to [Depot](https://depot.dev/) which make the cross-platform builds super fast; there must be something I can configure to make it work with forks. Or, at this point, I'll could just promote you to being able to push here...

**Comment by aneurinprice** [comment]
> there must be something I can configure to make it work with forks.

This is probably the correct way lmao

**Comment by Floppy** [comment]
Oooh I think I found the option... hopefully that will help :)

**Comment by Floppy** [comment]
Nice, looks like it did, I've tested it on another PR! Thanks for the prompt to fix it!

**Comment by aneurinprice** [comment]
No problem :) Keep up the great work! I love this project!

```
/libraries # du -sh *
101.4G	Decoration
1.3G	Functional
93.3M	Stencils
93.7M	Toys
```

I am using it all the time

**Pull request merged**
