### PR TITLE
Initial German translation

### LINKED ISSUE #1839: Full translation into German
German is the 5th most used language on the web according to https://www.statista.com/statistics/262946/most-common-languages-on-the-internet/. @ToasterUwU is helping out with this at the moment. If you'd like to help, sign up on https://translation.io, post your username, and I'll get you set up.

### PR DESCRIPTION
**Pull request by Floppy**
Done by @ToasterUwU. Resolves #1839.

### CODE REVIEW

**Comment by Floppy** [comment]
@ToasterUwU this is looking great! The German translations are coming in, and the fallback to English is working great too!

Screenshot 2024-02-08 at 11 49 24
Screenshot 2024-02-08 at 11 49 30
Screenshot 2024-02-08 at 11 49 52
Screenshot 2024-02-08 at 11 51 03

**Comment by ToasterUwU** [comment]
I assume this is a local instance? Just from the Screenshots alone that already helps so much for understanding the context.

**Comment by Floppy** [comment]
Yeah, this is in local development. If there are any bits it would be helpful to see, the quickest way at the moment is probably for me to do more screenshots, so feel free to ask :)

**Comment by ToasterUwU** [comment]
Thats fine, i can make a local setup as well without issues. Running Linux as my OS, so I can literally set it up with docker in no time.

**Comment by Floppy** [comment]
Ah, great - I don't tend to do local dev in Docker, so I've not really tried it with this app, but there's no reason it shouldn't work.

I've added the instructions to sync from translation.io to the README, though you'll need the API key. See if you can see it on https://translation.io/floppy/manyfold/settings, and set it in the `TRANSLATION_IO_API_KEY` env var.

**Comment by ToasterUwU** [comment]
I cant get the API Key it seems. 

TBH, the platform is fine in theory, but at the same time it makes it feel clunky to some degree. Im also not a huge fan of working on parts of a project that is managed with git, outside of git(hub/lab/tea/etc). You loose the history, you need people to sign up with another thing, then manually add them, then we cant see this in action without you sending screenshots, which makes it hard to figure out what to write there (I already have like 3 things I wanna improve just based on the few screenshots you made).

I would prefer something more integrated. Cause currently, having a yml file and manually editing it and having a local instance running and restarting to see changes would work better for me then the website thing ever could. 

I don't know if using this tool or another is even up for debate, but I wanted to say it either way.

Something like a Github action that runs a demo thing with translation if the PR is marked with "localisation" would be a better solution in my opinion

**Comment by ToasterUwU** [comment]
Im also not sure how this thing integrates, but API Key to get the translation working on my local instance sounds like its a external dependency on some API, which sounds like a bad idea in my opinion.

If it works like it sounds to me, that would mean that if this website goes under, is not reachable because of maintenance, revokes access for some reason, or the person using manyfold has this in the local net but no internet connection either by choice or not, this will need to default to english, even tho this is nothing more than some strings.  And that combined with the issues i have with it in the previous comment makes this a really bad choice in my eyes. 

Maybe i got the second part wrong, so don't take this as my set in stone opinion, I'm just assuming currently.

**Comment by ToasterUwU** [comment]
Glad to hear that feedback is appreciated for this.

The only benefit i can see for this is the DeepL translation part. Sometimes it gets it right and the string is done with one click, but other times its wrong and you have to manually write it out anyway.

I don't think the way it currently is, is worth the trouble of inviting and screenshots and all that.
Losing the history because its outside Github is a big thing for me as well.

Im also new to translations for software, the only things i ever worked on where either german or most of the times english only. 
But at least in theory it shouldn't be too hard to setup a workflow on github for this that just checks for the label in the PR and then sets up something like Heroku or something with a test instance using the branch of the PR. That way people can translate and get near instant feedback with the test instance.

**Comment by Floppy** [comment]
I think I'd like to stick with it for now, as I really want a way for users to contribute who aren't GitHub people. But, as I say, there's nothing to stop you pulling this branch down and working on it in the normal Rails way if that's what you prefer - it's all up to date with your latest work.

**Comment by ToasterUwU** [comment]
I see why you want that. But it's hard to imagine that the kind of people who have at least one 3D printer, use an open source project via docker on some sort of hosting machine, and want to help with translation, are not the kind of person who can with a simple step by step guide figure out which yml file to edit in which way.
To me this feels like preparing for something that is as likely as winning the lottery.

**Comment by Floppy** [comment]
I've just updated this PR again to the latest after I moved a few keys around. One thing though, I'm not getting any entries being created in `de` for the `active_admin`, `creators` and `collections` folders. I'll try to debug, but thought I'd let you know in case it was confusing.

**Comment by ToasterUwU** [comment]
@beniroqual Here is the PR, currently we use translation.io

**Comment by ToasterUwU** [comment]
@beniroquai Here is the PR, we use translation.io, at least for now

**Comment by beniroquai** [comment]
Got it thanks! Will have a look!

**Comment by Floppy** [comment]
Hey folks - I've deployed this branch to https://try.manyfold.app/, so you can see it all in action. I'll keep doing that whenever I sync the translations, normally a couple of times a day.

**Comment by Floppy** [comment]
With @beniroquai's latest translations (now deployed to https://try.manyfold.app) we're up to 80% translated into German! Thank you @ToasterUwU @beniroquai ❤️

**Comment by Floppy** [comment]
As we've reached 80% translated, I'm going to merge this into `main` and call it useful-enough-to-release. I'll bring in any further translations in future releases, of course.

**Comment by Floppy** [comment]
@beniroquai could I ask you to please accept the Contributor License Agreement? It's very simple, just says you're OK with releasing your work as MIT: https://cla-assistant.io/manyfold3d/manyfold?pullRequest=1844

**Comment by beniroquai** [comment]
Done! :) 
Impressive how professional you are doing this here! I'll try pushing it to the 100% :)

**Pull request merged**
