### PR TITLE
Preview image caching

### PR DESCRIPTION
**Pull request by Rukongai**
## Checklist

🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository. 🚨

- [x] Make sure you are making a pull request against our **main branch** (left side)
- [x] Check that that your branch is up to date with our main.
- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request *your* main!
- [x] Check that the tests and code linter both pass.
- [x] If you're a new contributor, please sign our [contributor license agreement](https://cla-assistant.io/manyfold3d/manyfold).

## Warnings

- [ ] This PR will change existing database contents.
- [ ] This PR introduces a breaking change to existing installations.

## Summary

Creates resized images to facilitate faster loading

## Description of changes

This creates a resized image of images to display on navigational pages (models, library, model files, etc)
Images are cached to tmp folder, I don't know if there is a better way of going about this but the change was pretty impactful for me. Maybe worth generating previews on discovery and attaching them to corresponding file in db?

Here are some before and after load times, loading a page with 24 items displayed

| Test# | Page 1 Before |  Page 1 After | Page 2 Before |  Page 2 After |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 1 | 5.09s | .863s | 12.43s | .794s |
| 2 | 8.94s | 1.25s | 9.79s | .775s |
| 3 | 3.74s | .762s | 8.67s | 1s |
| 4 | 5.73s |  .771s | 8.05s | 1.12s |

Let me know if you want me to pr this in earnest

### CODE REVIEW

**Comment by Rukongai** [comment]
BTW I have a docker image built with my dev branch which should encapsulate all the changes I have PRs open for at rukongai/manyfold:dev if that is at all convenient.

**Comment by Floppy** [comment]
Very nice, I like it! Some of those images can be really heavy, so this is a great idea.

Apologies I'm not getting through merging your PRs very quickly - my wife broke her arm, so I'm hardly getting any work time at the moment! Bear with me for a bit, I'll get there 😄

**Comment by Rukongai** [comment]
Sorry got sucked into a new project. I’m about to wrap it up and I’ll come back and clean all this up

**Comment by Floppy** [comment]
FYI, I'm working on a rewrite of the file backend using Shrine, which has built-in support for image resizing, so I suspect we won't need this in its current form. Sorry!

**Pull request closed without merging**
