### PR TITLE
Add a simple helm chart to deploy manyfold

### PR DESCRIPTION
**Pull request by aneurinprice**
## Checklist

🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository. 🚨

- [X] Make sure you are making a pull request against our **main branch** (left side)
- [X] Check that that your branch is up to date with our main.
- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request *your* main!
- [ ] Check that the tests and code linter both pass.
- [X] If you're a new contributor, please sign our [contributor license agreement](https://cla-assistant.io/manyfold3d/manyfold).

## Warnings

- [ ] This PR will change existing database contents.
- [ ] This PR introduces a breaking change to existing installations.

## Summary

This change introduces a basic helm chart to deploy Manyfold onto kubernetes via helm

## Description of changes

Added a helm chart to deploy manyfold onto kubernetes. Comes with bundled Redis and Postgresql helm charts provided by Bitnami. I will be improving this helm chart over the coming weeks, but this is a good start.

### CODE REVIEW

**Comment by Floppy** [comment]
This is cool, thank you! I wonder if it might be better in its own repo - what do you think? I'm no k8s best-practices expert...

**Comment by aneurinprice** [comment]
A dedicated helm charts repository might be a good idea. I currently have this chart in my own gitlab instance and am using it in my cluster. If you would like to go ahead and create a dedicated helm repository, I can push to that one?

**Comment by Floppy** [comment]
sounds good, I'll do that! ❤️

**Comment by Floppy** [comment]
OK, done: https://github.com/manyfold3d/helm-charts

**Comment by aneurinprice** [comment]
Awesome, I shall create a PR there.

**Pull request closed without merging**
